
services:
  app:
    build: .
    ports:
      - "8000:8000"  # Mapeia a porta do seu PC para a do container
    volumes:
      - .:/app       # Sincroniza seu código para o --reload funcionar
    env_file:
      - .env         # Carrega sua RIOT_API_KEY automaticamente
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload